# Visual.create(name: 'Rick', image_url: 'http://www.stickpng.com/assets/images/58f37709a4fa116215a9240d.png')
# Visual.create(name: 'Tardis', image_url: 'https://i.pinimg.com/originals/48/60/a8/4860a8b41f507aa4bd6d129221a174bc.png')
# Visual.create(name: 'Snape', image_url: 'https://vignette.wikia.nocookie.net/leonhartimvu/images/d/de/Severus_Snape_Pose.png/revision/latest?cb=20131019120341')
# Visual.create(name: 'Love', image_url: 'https://pre00.deviantart.net/ef71/th/pre/f/2013/122/f/8/the_stuff_song_by_sparkychloe-d63uaxb.png')

#  Visual.create(name: 'Love', image_url: '/images/visuals/ahule.gif')
 
#  Visual.create(name: 'Bed', image_url: '/images/visuals/bed.png')
#  Visual.create(name: 'Astronaut', image_url: '/images/visuals/astronaut.png')
#  Visual.create(name: 'Bird flying', image_url: '/images/visuals/bird_fly_big.gif')
#  Visual.create(name: 'Birds', image_url: '/images/visuals/birds.png')
#  Visual.create(name: 'Bysicle', image_url: '/images/visuals/bisycle.png')
#  Visual.create(name: 'Black Flowers', image_url: '/images/visuals/black_flowers.png')
#  Visual.create(name: 'Bricks', image_url: '/images/visuals/bricks.png')
#  Visual.create(name: 'Castle', image_url: '/images/visuals/castle.png')
#  Visual.create(name: 'Cloud Gif', image_url: '/images/visuals/cloud.gif')

#  Visual.create(name: 'Cloud', image_url: '/images/visuals/cloud2.png')
#  Visual.create(name: 'Coffee Spill', image_url: '/images/visuals/coffe_spill.png')
#  Visual.create(name: 'Couple', image_url: '/images/visuals/couple.png')
#  Visual.create(name: 'Craw', image_url: '/images/visuals/craw.gif')
#  Visual.create(name: 'Dancing Girl', image_url: '/images/visuals/dance_girl.gif')
#  Visual.create(name: 'David', image_url: '/images/visuals/david.jpeg')
#  Visual.create(name: 'Dementor', image_url: '/images/visuals/dementor.png')
#  Visual.create(name: 'Door Fancy', image_url: '/images/visuals/door_fancy.png')
#  Visual.create(name: 'Door Old', image_url: '/images/visuals/door_old.png')
#  Visual.create(name: 'Eyes Tears', image_url: '/images/visuals/eyes.png')

#  Visual.create(name: 'Fart', image_url: '/images/visuals/fart.png')
#  Visual.create(name: 'Firework', image_url: '/images/visuals/firework.gif')
#  Visual.create(name: 'Forest Black', image_url: '/images/visuals/forest_black.png')
#  Visual.create(name: 'Forest Green', image_url: '/images/visuals/forest_green.png')
#  Visual.create(name: 'Fox', image_url: '/images/visuals/fox_gif.gif')
#  Visual.create(name: 'Monster Fun', image_url: '/images/visuals/fun_monster.png')
#  Visual.create(name: 'Garden', image_url: '/images/visuals/garden.png')
#  Visual.create(name: 'Ghost', image_url: '/images/visuals/ghost_gif.gif')
#  Visual.create(name: 'Harry Potter', image_url: '/images/visuals/harrypotter.gif')
#  Visual.create(name: 'Hate', image_url: '/images/visuals/hate.png')

#  Visual.create(name: 'Kenny', image_url: '/images/visuals/kenny.gif')
#  Visual.create(name: 'Lamp', image_url: '/images/visuals/lamp.png')
#  Visual.create(name: 'Mars', image_url: '/images/visuals/mars.gif')
#  Visual.create(name: 'Marselina', image_url: '/images/visuals/marselina.png')
#  Visual.create(name: 'Mist', image_url: '/images/visuals/mist.png')
#  Visual.create(name: 'Monster', image_url: '/images/visuals/monster.png')
#  Visual.create(name: 'Moon', image_url: '/images/visuals/moon.gif')
#  Visual.create(name: 'Mountain', image_url: '/images/visuals/mountain.png')
#  Visual.create(name: 'Ohwow', image_url: '/images/visuals/ohwow.png')
#  Visual.create(name: 'Pagoda', image_url: '/images/visuals/pagoda.png')

#  Visual.create(name: 'Parrot', image_url: '/images/visuals/parrot.png')
#  Visual.create(name: 'Puppy', image_url: '/images/visuals/puppy_small.png')
#  Visual.create(name: 'River', image_url: '/images/visuals/river.png')
#  Visual.create(name: 'Roket', image_url: '/images/visuals/roket.gif')
#  Visual.create(name: 'Castle Sand', image_url: '/images/visuals/sand_castle.png')
#  Visual.create(name: 'Sex', image_url: '/images/visuals/sex.png')
#  Visual.create(name: 'Sos', image_url: '/images/visuals/sos.png')
#  Visual.create(name: 'Space', image_url: '/images/visuals/space.png')
#  Visual.create(name: 'Tornado', image_url: '/images/visuals/tornado.gif')
#  Visual.create(name: 'Volcano', image_url: '/images/visuals/volcano.gif')
# Visual.create(name: 'Cloud Big', image_url: '/images/visuals/cloud_big.png')
# Visual.create(name: 'Black Hole', image_url: '/images/visuals/black_hole.png')
# Visual.create(name: 'Girl One', image_url: '/images/visuals/girl1.png')
# Visual.create(name: 'Books', image_url: '/images/visuals/books.png')
# Visual.create(name: 'Rocket One', image_url: '/images/visuals/rocket2.png')
# Visual.create(name: 'Rain Cloud', image_url: '/images/visuals/rain.gif')
# Visual.create(name: 'Treasure', image_url: '/images/visuals/treasure.png')

# Visual.create(name: 'Stairs', image_url: '/images/visuals/stairs.png')
# Visual.create(name: 'Astronaut Gif', image_url: '/images/visuals/astronaut_gif.gif')
# Visual.create(name: 'Music Gif', image_url: '/images/visuals/music.gif')

# Visual.create(name: 'Water', image_url: '/images/visuals/water1.png')
# Visual.create(name: 'Water2', image_url: '/images/visuals/water2.png')

Visual.create(name: 'Flowers Black 2', image_url: '/images/visuals/flowers.png')
Visual.create(name: 'Flowers Black 3', image_url: '/images/visuals/flowers2.png')
Visual.create(name: 'Tree Black', image_url: '/images/visuals/treeblack.png')
Visual.create(name: 'Tardis', image_url: '/images/visuals/tardis.gif')